# 基础镜像
FROM nginx
# author
MAINTAINER Ken

# 挂载目录
VOLUME /home/pinpoint/web
# 创建目录
RUN mkdir -p /home/pinpoint/web
# 指定路径
WORKDIR /home/pinpoint/web

# 复制html文件到路径
COPY ./dist /home/pinpoint/web

